name: cicd
on:
  workflow_dispatch:
   inputs:
      environment:
        description: 'this is the envorment value where this workflow run'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - qa
jobs:
  code:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        run: echo "code clone from github"
  build:
    runs-on: ubuntu-latest
    steps:
      - name: buid docker container
        run: echo "docker container buo=ild"
  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: test the container
        run: echo "testing the container"
  deploy:
    if: inputs.envorment == 'dev'
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: deploy the app
        run: echo "docker compose deployed the app"
