---
name: cicd
on:
  workflow_dispatch: null
jobs:
  code:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        run: echo "code clone from github"
  build:
    runs-on: ubuntu-latest
    steps:
      - name: buid docker container
        run: echo "docker container buo=ild"
  test:
    runs-on: ubuntu-latest
    steps:
      - name: test the container
        run: echo "testing the container"
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: deploy the app
        run: echo "docker compose deployed the app"
