

name: hello workflow

on:
  push: branchs:[main]
jobs:

  greet:
    run-on: ubuntu-latest
    
    steps:
    
      - name: say hello to user
        run: echo "hello shailendra"
        
      - name: say hello to usernme
        run: echo "hello $USER"
