---
name: hello workflow
on:
  workflow-dispatch:
jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: say hello to user
        run: echo "hello shailendra"
      - name: say hello to usernme
        run: echo "hello $USER"
  details:
    runs-on: ubuntu-latest
    steps:
      - name: versions
        run: docker --version && python --version
